name: drup
description: "A ride-hailing mobile application with Google Maps integration."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.2
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_polyline_points: ^3.1.0
  
  # HTTP & API
  http: ^1.2.0
  
  # Utils
  uuid: ^4.3.3
  intl: ^0.19.0
  permission_handler: ^11.2.0
  flutter_dotenv: ^5.1.0
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  cloud_functions: ^6.0.4
  firebase_messaging: ^16.0.4
  gap: ^3.0.1
  the_validator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/flags/
    - assets/icons/
    - assets/others/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: fonts/RedHatDisplay-Light.ttf
          weight: 200
        - asset: fonts/RedHatDisplay-Regular.ttf
          weight: 400
        - asset: fonts/RedHatDisplay-SemiBold.ttf
          weight: 500
        - asset: fonts/RedHatDisplay-Medium.ttf
          weight: 600
        - asset: fonts/RedHatDisplay-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

    - family: DrupIcons
      fonts:
        - asset: fonts/Drup-icons.ttf